### PR TITLE
Stage 1 - Submission for review

### PR DESCRIPTION
**Pull request by lindakovacs**

### CODE REVIEW

**Comment by AygulMalikova** [comment]
Unfortunately, your work is rejected without review once again since when you try to send any request on your remote server or if I run your project and send locally, there is always an error with code 500: **"An error has occured on the server"**. Please check that all requests are working fine.

**Comment by lindakovacs** [comment]
@AygulMalikova Unfortunately, before I took an academic leave for personal reasons I had almost the whole project ready: stage-1 and stage-2 fully working and in progress the stage-3. When I came back to my code after a month I didn't realize that after my code was working fine a month ago it didn't save somehow. I was able to fix it and I re-submit it but I'm not sure if I submitted the right link and there is no way in the platform to check that. Could you please confirm that you have the right link? Thank you and I apologize for the inconveniences, Linda

**Comment by AygulMalikova** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
    - [x] A  package.json file.
    - [x] An .editorconfig file.
    - [x] An .eslintrc file, which extends the airbnb-base configuration, and devDependencies required for the linter.
    - [x] A .gitignore file.
    - [x] Additionally, an exception for `_id` is added in .eslintrc. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
- [x]  No linting errors.
- [x]  The scripts section of the package.json file contains the following:
    - [x] An `npm run start` command that starts the server on `localhost:3000`.
    - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  When all dependencies are installed, the application starts with npm run dev without errors.
- [ ]  The following routes function as described:
    - [ ] A request to `GET /users/me` returns information about the user (email and name).
      **There is Internal Server Error**
    - [x] `GET /articles` returns all articles saved by the user.
    - [ ] `POST /articles` creates an article with the data passed inside the request body.
      **There is Internal Server Error**
    - [ ] `DELETE /articles/articleId` deletes the saved article using `_id`.
      **I can not check the card removing since I may not create a card**
    - [x] `POST /signup` creates a user with the data passed inside the request body.
    - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [ ]  API errors are handled:
    - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
    - [ ] Asynchronous handlers end with a `catch()` block.
    - [ ] The API does not return standard database or Node.js errors.
    **Please check that your server responds with the correct error message and a corresponding status instead of just 500 - Internal Error. **
      Please also note that you need to return an error as a JSON with message instead of HTML as it is now.**
- [x]  In production mode, the database address is taken from `process.env`.
- [ ]  Safe password storage has been implemented:
    - [x] Passwords are stored in an encrypted format.
    - [ ] The API does not return a password hash to the client.
      **Please remove alphanum restriction on the password. And do not return the hash of the password when you create a user**
- [x]  Data is validated before being added to the database.
- [ ]  Users can't delete saved cards from other user profiles.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md. 
- [x]  Storing the private key for creating a JWT is implemented correctly:
    - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
    - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine and an error won't occur if there is no `.env` file present.

### Best Practices
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
- [x]  Logging is set up:
    - [x] All requests and responses are logged to the `request.log` file.
    - [x] All errors are logged to the `error.log` file.
    - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [ ]  In case of an error, the API returns a response status that matches the error type.
- [x]  The server can be accessed via HTTPS using the domain specified in `README.md`. 
- [ ]  The application API is located on a domain with a name of the following format: name.zone/api (not just name.zone).
    - [ ] Correct: news-explorer.tk/api
    - [ ] Incorrect: news-explorer.tk
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.

### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
    - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
    - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into app.js.
- [ ]  The API is hosted on a separate subdomain, e.g. api.news-explorer.tk.

## Number of points:
57

## Additional comments:
Good job! But there are some small remarks. First of all, I ask you to note that now some requests are not working correctly (getting user information, creating a card). Please check that your server responds with the correct error message and a corresponding status instead of just 500 - Internal Error. 
I remind you that the work will be accepted as soon as you receive at least 80 points. Wish you luck!

**Comment by AygulMalikova** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
    - [x] A  package.json file.
    - [x] An .editorconfig file.
    - [x] An .eslintrc file, which extends the airbnb-base configuration, and devDependencies required for the linter.
    - [x] A .gitignore file.
    - [x] Additionally, an exception for `_id` is added in .eslintrc. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
- [x]  No linting errors.
- [x]  The scripts section of the package.json file contains the following:
    - [x] An `npm run start` command that starts the server on `localhost:3000`.
    - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  When all dependencies are installed, the application starts with npm run dev without errors.
- [ ]  The following routes function as described:
    - [x] A request to `GET /users/me` returns information about the user (email and name).
      **Please do not return the hash of the password with user information**
    - [x] `GET /articles` returns all articles saved by the user.
    - [x] `POST /articles` creates an article with the data passed inside the request body.
    - [ ] `DELETE /articles/articleId` deletes the saved article using `_id`.
      **When I try to remove an article (i.e. http://lkovacs-news.students.nomoreparties.site/articles/608fb4b9b8515b90111ed8d4) then I receive the error: \"id\" is required**
    - [x] `POST /signup` creates a user with the data passed inside the request body.
    - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
    - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
    - [x] Asynchronous handlers end with a `catch()` block.
    - [x] The API does not return standard database or Node.js errors.
- [x]  In production mode, the database address is taken from `process.env`.
- [ ]  Safe password storage has been implemented:
    - [x] Passwords are stored in an encrypted format.
    - [ ] The API does not return a password hash to the client.
      **Please do not return the hash of the password with user information**
- [x]  Data is validated before being added to the database.
- [ ]  Users can't delete saved cards from other user profiles.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md. 
- [x]  Storing the private key for creating a JWT is implemented correctly:
    - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
    - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine and an error won't occur if there is no `.env` file present.

### Best Practices
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
- [x]  Logging is set up:
    - [x] All requests and responses are logged to the `request.log` file.
    - [x] All errors are logged to the `error.log` file.
    - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  In case of an error, the API returns a response status that matches the error type.
- [x]  The server can be accessed via HTTPS using the domain specified in `README.md`. 
- [ ]  The application API is located on a domain with a name of the following format: name.zone/api (not just name.zone).
    - [ ] Correct: news-explorer.tk/api
    - [ ] Incorrect: news-explorer.tk
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.

### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
    - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
    - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into app.js.
- [ ]  The API is hosted on a separate subdomain, e.g. api.news-explorer.tk.

## Number of points:
65

## Additional comments:
Very well! You've fixed a lot of bugs and you're heading in the right direction!
Please check that an article removing works correctly. Good luck!

**Comment by AygulMalikova** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
    - [x] A  package.json file.
    - [x] An .editorconfig file.
    - [x] An .eslintrc file, which extends the airbnb-base configuration, and devDependencies required for the linter.
    - [x] A .gitignore file.
    - [x] Additionally, an exception for `_id` is added in .eslintrc. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
- [x]  No linting errors.
- [x]  The scripts section of the package.json file contains the following:
    - [x] An `npm run start` command that starts the server on `localhost:3000`.
    - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  When all dependencies are installed, the application starts with npm run dev without errors.
- [x]  The following routes function as described:
    - [x] A request to `GET /users/me` returns information about the user (email and name).
    - [x] `GET /articles` returns all articles saved by the user.
    - [x] `POST /articles` creates an article with the data passed inside the request body.
    - [x] `DELETE /articles/articleId` deletes the saved article using `_id`.
      **When I try to remove an article (i.e. http://lkovacs-news.students.nomoreparties.site/articles/608fb4b9b8515b90111ed8d4) then I receive the error: \"id\" is required**
    - [x] `POST /signup` creates a user with the data passed inside the request body.
    - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [x]  API errors are handled:
    - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
    - [x] Asynchronous handlers end with a `catch()` block.
    - [x] The API does not return standard database or Node.js errors.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  Safe password storage has been implemented:
    - [x] Passwords are stored in an encrypted format.
    - [x] The API does not return a password hash to the client.
- [x]  Data is validated before being added to the database.
- [x]  Users can't delete saved cards from other user profiles.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md. 
- [x]  Storing the private key for creating a JWT is implemented correctly:
    - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
    - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine and an error won't occur if there is no `.env` file present.

### Best Practices
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
- [x]  Logging is set up:
    - [x] All requests and responses are logged to the `request.log` file.
    - [x] All errors are logged to the `error.log` file.
    - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  In case of an error, the API returns a response status that matches the error type.
- [x]  The server can be accessed via HTTPS using the domain specified in `README.md`. 
- [ ]  The application API is located on a domain with a name of the following format: name.zone/api (not just name.zone).
    - [ ] Correct: news-explorer.tk/api
    - [ ] Incorrect: news-explorer.tk
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.

### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
    - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
    - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into app.js.
- [ ]  The API is hosted on a separate subdomain, e.g. api.news-explorer.tk.

## Number of points:
97

## Additional comments:
Congratulations, you have successfully completed the backend stage of your final project! In your project, there is still an opportunity to improve it, and it would be great if you fix them yourself (see the checklist). I was glad to check your work. I wish you success!

**Comment by lindakovacs** [comment]
Thank you so much! It was a pleasure to have you as a reviewer for many of my projects during the curriculum. I hope to meet you on the next stages for the front end. I wish you all the best! During the weekend I might take care of the remaining items but I will submit the stage-2 for review in meantime since it is ready.

**Comment by AygulMalikova** [comment]
Linda, thank you for your feedback!❤️ I am always pleased to work with you. I wish you successful completion of the next stages, hope we will meet at stage-3 with React!

**Pull request merged**
